=== 217868/DataIntegrationProject/films.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT film_base (film)+>

<!ELEMENT film (title,release_date_in_USA,countries,directors,cast,
                duration_in_minutes,distributors,languages,
                music_authors,box_office)>
<!ATTLIST film
  image_link CDATA #REQUIRED
  year CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT release_date_in_USA (#PCDATA)>

<!ELEMENT countries (country)+>

<!ELEMENT directors (director)+>

<!ELEMENT cast (actor)+>

<!ELEMENT duration_in_minutes (#PCDATA)>

<!ELEMENT distributors (distributor)+>

<!ELEMENT languages (language)+>

<!ELEMENT music_authors (musicAuthor)+>

<!ELEMENT box_office (#PCDATA)>

<!ELEMENT country (#PCDATA)>

<!ELEMENT director (#PCDATA)>

<!ELEMENT actor (#PCDATA)>

<!ELEMENT distributor (#PCDATA)>

<!ELEMENT language (#PCDATA)>

<!ELEMENT musicAuthor (#PCDATA)>

=== 217868/DataIntegrationProject/films.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE film_base SYSTEM "films.dtd">
<?xml-stylesheet type = "text/xsl" href = "directors_with_films.xsl"?>
<film_base>
     <film image_link="https://upload.wikimedia.org/wikipedia/en/a/a0/A_Quiet_Place_film_poster.png" year="2018">
          <title>A Not So Quiet Place</title>
          <release_date_in_USA>2018-04-06</release_date_in_USA>
          <countries>
               <country>United States</country>
          </countries>
          <directors>
               <director>John Krasinski</director>
          </directors>
          <cast>
               <actor>Emily Blunt</actor>
               <actor>John Krasinski</actor>
          </cast>
          <duration_in_minutes>90</duration_in_minutes>
          <distributors>
               <distributor>Paramount Pictures</distributor>
          </distributors>
          <languages>
               <language>American Sign Language</language>
               <language>English</language>
          </languages>
          <music_authors>
               <musicAuthor>Marco Beltrami</musicAuthor>
          </music_authors>
          <box_office>340.9</box_office>
     </film>
     <film image_link="https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Thelma_%26_Louise_poster.png/220px-Thelma_%26_Louise_poster.png" year="1991">
          <title>Thelma &amp;amp; Louise</title>
          <release_date_in_USA>1991-05-24</release_date_in_USA>
          <countries>
               <country>United States</country>
          </countries>
          <directors>
               <director>Ridley Scott</director>
          </directors>
          <cast>
               <actor>Susan Sarandon</actor>
               <actor>Geena Davis</actor>
               <actor>Harvey Keitel</actor>
          </cast>
          <duration_in_minutes>129</duration_in_minutes>
          <distributors>
               <distributor>Metro-Goldwyn-Mayer</distributor>
          </distributors>
          <languages>
               <language>English</language>
          </languages>
          <music_authors>
               <musicAuthor>Hans Zimmer</musicAuthor>
          </music_authors>
          <box_office>45.4</box_office>
     </film>
     <film image_link="https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Blade_Runner_%281982_poster%29.png/220px-Blade_Runner_%281982_poster%29.png" year="1982">
          <title>Blade Runner</title>
          <release_date_in_USA>1982-06-25</release_date_in_USA>
          <countries>
               <country>United States</country>
               <country>Hong Kong</country>
          </countries>
          <directors>
               <director>Ridley Scott</director>
          </directors>
          <cast>
               <actor>Harrison Ford</actor>
               <actor>Rutger Hauer</actor>
               <actor>Sean Young</actor>
               <actor>Edward James Olmos</actor>
          </cast>
          <duration_in_minutes>117</duration_in_minutes>
          <distributors>
               <distributor>Warner Bros.</distributor>
          </distributors>
          <languages>
               <language />
          </languages>
          <music_authors>
               <musicAuthor>Vangelis</musicAuthor>
          </music_authors>
          <box_office>41.5</box_office>
     </film>
     <film image_link="https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Alien_movie_poster.jpg/220px-Alien_movie_poster.jpg" year="1979">
          <title>Alien</title>
          <release_date_in_USA>1979-05-25</release_date_in_USA>
          <countries>
               <country>United Kingdom</country>
               <country>United States</country>
          </countries>
          <directors>
               <director>Ridley Scott</director>
          </directors>
          <cast>
               <actor>Tom Skerritt</actor>
               <actor>Sigourney Weaver</actor>
               <actor>Veronica Cartwright</actor>
               <actor>Harry Dean Stanton</actor>
               <actor>John Hurt</actor>
               <actor>Ian Holm</actor>
               <actor>Yaphet Kotto</actor>
          </cast>
          <duration_in_minutes>117</duration_in_minutes>
          <distributors>
               <distributor>20th Century Fox</distributor>
          </distributors>
          <languages>
               <language>English</language>
          </languages>
          <music_authors>
               <musicAuthor>Jerry Goldsmith</musicAuthor>
          </music_authors>
          <box_office>203.6</box_office>
     </film>
     <film image_link="https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Back_to_the_Future.jpg/220px-Back_to_the_Future.jpg" year="1985">
          <title>Back to the Future</title>
          <release_date_in_USA>1985-07-03</release_date_in_USA>
          <countries>
               <country>United States</country>
          </countries>
          <directors>
               <director>Robert Zemeckis</director>
          </directors>
          <cast>
               <actor>Michael J. Fox</actor>
               <actor>Christopher Lloyd</actor>
               <actor>Lea Thompson</actor>
               <actor>Crispin Glover</actor>
          </cast>
          <duration_in_minutes>116</duration_in_minutes>
          <distributors>
               <distributor>Universal Pictures</distributor>
          </distributors>
          <languages>
               <language>English</language>
          </languages>
          <music_authors>
               <musicAuthor>Alan Silvestri</musicAuthor>
          </music_authors>
          <box_office>389.1</box_office>
     </film>
     <film image_link="https://upload.wikimedia.org/wikipedia/en/thumb/6/66/E_t_the_extra_terrestrial_ver3.jpg/220px-E_t_the_extra_terrestrial_ver3.jpg" year="1982">
          <title>E.T. the Extra-Terrestrial</title>
          <release_date_in_USA>1982-06-11</release_date_in_USA>
          <countries>
               <country>United States</country>
          </countries>
          <directors>
               <director>Steven Spielberg</director>
          </directors>
          <cast>
               <actor>Dee Wallace</actor>
               <actor>Peter Coyote</actor>
               <actor>Henry Thomas</actor>
          </cast>
          <duration_in_minutes>114</duration_in_minutes>
          <distributors>
               <distributor>Universal Pictures</distributor>
          </distributors>
          <languages>
               <language>English</language>
          </languages>
          <music_authors>
               <musicAuthor>John Williams</musicAuthor>
          </music_authors>
          <box_office>792.9</box_office>
     </film>
     <film image_link="https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Good_Will_Hunting.png/220px-Good_Will_Hunting.png" year="1997">
          <title>Good Will Hunting</title>
          <release_date_in_USA>1997-12-05</release_date_in_USA>
          <countries>
               <country>United States</country>
          </countries>
          <directors>
               <director>Gus Van Sant</director>
          </directors>
          <cast>
               <actor>Robin Williams</actor>
               <actor>Matt Damon</actor>
               <actor>Ben Affleck</actor>
               <actor>Stellan Skarsg√•rd</actor>
               <actor>Minnie Driver</actor>
          </cast>
          <duration_in_minutes>126</duration_in_minutes>
          <distributors>
               <distributor>Miramax Films</distributor>
          </distributors>
          <languages>
               <language>English</language>
          </languages>
          <music_authors>
               <musicAuthor>Danny Elfman</musicAuthor>
          </music_authors>
          <box_office>225.9</box_office>
     </film>
     <film image_link="https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Talented_mr_ripley.jpg/220px-Talented_mr_ripley.jpg" year="1999">
          <title>The Talented Mr. Ripley</title>
          <release_date_in_USA>1999-12-25</release_date_in_USA>
          <countries>
               <country>United States</country>
          </countries>
          <directors>
               <director>Anthony Minghella</director>
          </directors>
          <cast>
               <actor>Matt Damon</actor>
               <actor>Gwyneth Paltrow</actor>
               <actor>Jude Law</actor>
               <actor>Cate Blanchett</actor>
               <actor>Philip Seymour Hoffman</actor>
               <actor>Jack Davenport</actor>
               <actor>James Rebhorn</actor>
               <actor>Sergio Rubini</actor>
               <actor>Philip Baker Hall</actor>
          </cast>
          <duration_in_minutes>139</duration_in_minutes>
          <distributors>
               <distributor>Paramount Pictures</distributor>
               <distributor>Miramax Films</distributor>
          </distributors>
          <languages>
               <language>English</language>
          </languages>
          <music_authors>
               <musicAuthor>Gabriel Yared</musicAuthor>
          </music_authors>
          <box_office>0.0</box_office>
     </film>
     <film image_link="https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/The_accidental_tourist.jpg/220px-The_accidental_tourist.jpg" year="1988">
          <title>The Accidental Tourist</title>
          <release_date_in_USA>1988-12-23</release_date_in_USA>
          <countries>
               <country>United States</country>
          </countries>
          <directors>
               <director>Lawrence Kasdan</director>
          </directors>
          <cast>
               <actor>William Hurt</actor>
               <actor>Kathleen Turner</actor>
               <actor>Geena Davis</actor>
               <actor>Bill Pullman</actor>
          </cast>
          <duration_in_minutes>121</duration_in_minutes>
          <distributors>
               <distributor>Warner Bros.</distributor>
          </distributors>
